name: Docker Build and Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    IMAGE_NAME: rickfast/hollowgear

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: false
                  tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Start container
              run: |
                  docker run -d -p 8080:80 --name test-container ${{ env.IMAGE_NAME }}:${{ github.sha }}
                  sleep 5

            - name: Test health endpoint
              run: |
                  curl -f http://localhost:8080/health || exit 1

            - name: Test main page
              run: |
                  curl -f http://localhost:8080/ || exit 1

            - name: Check container logs
              if: failure()
              run: docker logs test-container

            - name: Stop container
              if: always()
              run: docker stop test-container

    # Optional: Push to container registry
    # push:
    #   needs: build
    #   runs-on: ubuntu-latest
    #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    #
    #   steps:
    #     - name: Checkout code
    #       uses: actions/checkout@v4
    #
    #     - name: Log in to Container Registry
    #       uses: docker/login-action@v3
    #       with:
    #         registry: ghcr.io
    #         username: ${{ github.actor }}
    #         password: ${{ secrets.GITHUB_TOKEN }}
    #
    #     - name: Build and push
    #       uses: docker/build-push-action@v5
    #       with:
    #         context: .
    #         push: true
    #         tags: |
    #           ghcr.io/${{ github.repository }}:latest
    #           ghcr.io/${{ github.repository }}:${{ github.sha }}
